version: '3'

services:
  converter:
    build: .
    container_name: "miniseed-to-parquet-converter-ZZ"
    volumes:
      - /mnt/data:/app/data
      - /mnt/code/output:/app/output
    command: python main.py
