version: '3'

services:
  converter:
    build: .
    container_name: "miniseed-to-parquet-converter-ZZ"
    volumes:
      - /mnt/data:/app/data
      - /mnt/code/output:/app/output
    command: python main.py

volumes:
  input_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/data

  output_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/code/output
