version: "3"

services:
  converter-2:
    build: .
    container_name: "miniseed-to-parquet-converter-ZB"
    volumes:
      - /mnt:/mnt
      - /mnt/code/output:/mnt/code/output
    command: python /notebooks/mseed_parquet_ZB.py

volumes:
  input_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt

  output_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/code/output
