version: '3'

services:
  converter:
    build: .
    container_name: "miniseed-to-parquet-converter-ZB"
    volumes:
      - /mnt:/mnt
      - /mnt/code/output:/mnt/code/output
    command: python /app/mseed_parquet_ZB.py
    deploy:
      resources:
        limits:
          memory: 3G
