version: '3'

services:
  server:
    build: .
    container_name: "parquet-server"
    volumes:
      - /mnt/:/mnt/
    ports:
      - "5000:5000"

  converter:
    build: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY