   version: "3"

   services:
     converter:
       build: .
       container_name: "miniseed-to-parquet-converter"
       volumes:
         - /path/on/host:/mnt/data/SWP_Seismic_Database_Current
         - /mnt/code/output:/mnt/code/output
       command: python /app/mseed_parquet.py