version: '3'

services:
  converter:
    build: .
    container_name: miniseed-to-parquet-converter
    volumes:
      - type: bind
        source: /mnt
        target: /mnt
      - type: bind
        source: /mnt/code/output
        target: /mnt/code/output
    command: python /app/convert_miniseed_to_parquet.py

volumes:
  input_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt
  output_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/code/output
