services:
  mseed_parquet_local:
    build: .
    container_name: "mseed-parquet-local"
    volumes:
      - /mnt/:/mnt/
      - /mnt/f/parquet/:/mnt/f/parquet/
    ports:
      - "4999:5010"
    command: python mseed_parquet_local.py
    deploy:
      resources:
        limits:
          memory: 2G

  mseed_parquet_local_2:
    build: .
    container_name: "mseed-parquet-local-2"
    volumes:
      - /mnt/:/mnt/
      - /mnt/f/parquet/:/mnt/f/parquet/
    ports:
      - "5001:5010"
    command: python mseed_parquet_local_2.py
    deploy:
      resources:
        limits:
          memory: 2G

  mseed_parquet_local_3:
    build: .
    container_name: "mseed-parquet-local-3"
    volumes:
      - /mnt/:/mnt/
      - /mnt/f/parquet/:/mnt/f/parquet/
    ports:
      - "5002:5010"
    command: python mseed_parquet_local_3.py
    deploy:
      resources:
        limits:
          memory: 2G
