version: "3"

services:
  converter:
    build: .
    container_name: "miniseed-to-parquet-converter"
    volumes:
      - input_data:/mnt
      - output_data:/mnt/code/output
    command: python /app/mseed_parquet.py

volumes:
  input_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt
  output_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/code/output