version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - /mnt/data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
