version: '3'

services:
  server:
    build: .
    container_name: "parquet-server"
    volumes:
      - /mnt/:/mnt/
    ports:
      - "5000:5000"

  converter:
    build:
      context: .
    container_name: "seismic-converter"
    volumes:
      - /mnt/:/mnt/