version: "3"
services:
  data-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-container
    volumes:
      - /mnt:/mnt
    command: ["sh", "-c", "sleep infinity"]
