version: '3'

services:
  nginx:
    build: .
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - /mnt/:/usr/share/nginx/html/mnt/
    command: ["nginx", "-g", "daemon off;"]
